# Generated by Django 4.2.2 on 2023-06-16 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_productreview'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productreview',
            options={'verbose_name_plural': 'Reviews'},
        ),
    ]
