# Generated by Django 4.2.2 on 2023-06-16 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_productreview_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'verbose_name_plural': ' ➢ Banners'},
        ),
        migrations.AlterModelOptions(
            name='brand',
            options={'verbose_name_plural': ' ➢ Brands'},
        ),
        migrations.AlterModelOptions(
            name='cartorder',
            options={'verbose_name_plural': ' ➢ Orders'},
        ),
        migrations.AlterModelOptions(
            name='cartorderitems',
            options={'verbose_name_plural': ' ➢ Order Items'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': ' ➢ Categories'},
        ),
        migrations.AlterModelOptions(
            name='color',
            options={'verbose_name_plural': ' ➢ Colors'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name_plural': ' ➢ Products'},
        ),
        migrations.AlterModelOptions(
            name='productattribute',
            options={'verbose_name_plural': ' ➢ Product Attributes'},
        ),
        migrations.AlterModelOptions(
            name='productreview',
            options={'verbose_name_plural': ' ➢ Product Reviews'},
        ),
        migrations.AlterModelOptions(
            name='size',
            options={'verbose_name_plural': ' ➢ Sizes'},
        ),
    ]
