# Generated by Django 4.2.1 on 2023-06-17 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_useraddressbook'),
    ]

    operations = [
        migrations.AddField(
            model_name='productattribute',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
