# Generated by Django 4.2.1 on 2023-06-17 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_productattribute_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productattribute',
            name='stock',
        ),
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
